### ISSUE TITLE
Segfault on TempAllocator.reset from @pool()

### ISSUE THREAD

**Issue by hwchen** [c3lang/c3c#1462]
```
(gdb) backtrace
#0  0x00000000004328c8 in std.core.mem.allocator.TempAllocator.reset (self=0x7ffff7c95010, mark=136)
    at /nix/store/ncv46wwhpya58snvmlvymvpazhz6vzpi-c3c-0.6.2/lib/c3/std/core/allocators/temp_allocator.c3:83
#1  0x000000000040743c in @pool () at /nix/store/ncv46wwhpya58snvmlvymvpazhz6vzpi-c3c-0.6.2/lib/c3/std/core/mem.c3:523
#2  segfault.main () at segfault.c3:11
#3  0x00000000004074a2 in @main_to_void_main ()
    at /nix/store/ncv46wwhpya58snvmlvymvpazhz6vzpi-c3c-0.6.2/lib/c3/std/core/private/main_stub.c3:18
#4  main (.anon=0x7fffffffb488, .anon=0x7fffffffb488) at segfault.c3:8
```
```
module segfault;

import std::collections::map;

const int LIMIT = 100000;

fn void main() {
    map::HashMap(<long, char>) set;
    set.temp_init();
    @pool() {
        for (long i; i < LIMIT; i++) {
            set.set(i, 0);
        }
    };
}
```
```
c3c compile segfault.c3
```
Probably not the smallest reproduction, but the snippet is derived from the project I was working on. Lowering the limit does not trigger segfault on my computer (Ubuntu 22.04 amd64).

Let me know if there's anything else I can do. Might try to look at this if I have time.

**Comment by lerno** [comment]
Thank you for finding this! I've issued a fix, please check that it is handled in the latest build.

**Comment by hwchen** [comment]
Looks like it works!
